apiVersion: v2
name: "{{ project_slug }}"
version: 1.0.0
dependencies:
- name: tripster-app
  alias: "{{ project_slug }}"
  export-values:
  - parent: werf
    child: werf
  repository: "@helm-tripster-app"
  version: "{{ helm_chart_version }}"
{%- if worker == 'dramatiq' %}
- name: tripster-app
  alias: dramatiq-worker
  export-values:
  - parent: werf
    child: werf
  repository: "@helm-tripster-app"
  version: "{{ helm_chart_version }}"
{%- endif %}
{%- if event_bus_consumer == 'faststream' %}
- name: tripster-app
  alias: faststream
  export-values:
  - parent: werf
    child: werf
  repository: "@helm-tripster-app"
  version: "{{ helm_chart_version }}"
{%- endif %}
