.env_template: &env
  env:
    SENTRY_DSN: ""
{%- if broker == 'rabbitmq' %}
    RABBITMQ_PASSWORD: ""
{%- endif %}
{{ project_slug }}:
  !!merge <<: *env
{%- if worker == 'dramatiq' %}
dramatiq-worker:
  !!merge <<: *env
{%- endif %}
{%- if event_bus_consumer == 'faststream' %}
faststream:
  !!merge <<: *env
{%- endif %}
